[package]
name = "hyperv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
powershell-rs = { path = "../powershell-rs" }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
